version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  eureka:
    image: eureka-server:latest
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  product-service:
    image: product-service:latest
    build:
      context: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - eureka
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  order-service:
    image: order-service:latest
    build:
      context: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - eureka
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  inventory-service:
    image: inventory-service:latest
    build:
      context: ./inventory-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - eureka
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  notification-service:
    image: notification-service:latest
    build:
      context: ./notification-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - eureka
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  postgres_data: