spring:
  application:
    name: auth-service
  profiles:
    active: dev
eureka:
  client:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html