server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: ecommerce-realm
  resource: ecommerce-client
  credentials:
    secret: your-client-secret-here
  public-client: false
  bearer-only: false