global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['eureka:8761']
  - job_name: 'product-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['product-service:8081']
  - job_name: 'order-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['order-service:8082']
  - job_name: 'inventory-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['inventory-service:8083']
  - job_name: 'notification-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['notification-service:8084']
  - job_name: 'search-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['search-service:8085']
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8080']
  - job_name: 'auth-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['auth-service:8086']