spring:
  application:
    name: search-service
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
server:
  port: 8085