spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: search-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: elasticsearch:9200
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
server:
  port: 8085