spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: kafka:9092
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/