spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/